baseurl                 = "http://highereddashboards.io/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Maureen Wynne"
theme                   = "sam"
pygmentsStyle           = "manni"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    homepage            = "Main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Maureen Wynne"

# Metadata
    description         = "Maureen Wynne"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/about"
    text = "Maureen Wynne"

[[params.mainMenu]]
    link = "/work"
    text = "Work"

[[params.mainMenu]]
    link = "/contact"
    text = "Contact"
